### ISSUE TITLE
Code-first approach

### ISSUE THREAD

**Issue by turowicz** [MiracleDevs/Paradigm.ORM#2]
Hey @pabloordonez @lbrugnara @bgrainger

First let me say BIG THANK YOU for the great work you did on the Paradigm ORM.

Are you planning on introducing a code-first approach for the ORM? 

It would be very helpful to be able to generate the database schema for deploying new tables. 

I don't mean the migrations where you would need to generate a diff script for the database.

**Comment by pabloordonez** [comment]
Hey @turowicz thanks! 

To tell you the truth, It wasn't in our plans, mostly because we started this as way or get back DbFirst, as stated in the [documentation](https://www.paradigm.net.co/articles/1.introduction/index.html).

Originally (like 3 or 4 years ago) when we started this, we were mostly interested into design the database in the database and not the other way around. In our experience DbFirst stimulates bad coding practices, db without the proper structure, and a abuse of Linq where one should use Stored Procedures and Db objects.

But I definitely can see the advantage of being able to kickstart a quick project. We do have most of the information required in the form of Attributes decorating the types. We could use that to produce a valid script. We would also need to modify (add) each db format provider in order for us to get the proper DDL syntax for each database. As a quick example, creating a table in MySql could be as simple as: 

```SQL
CREATE TABLE IF NOT EXISTS `my:_table`  (...) ;
```

But in the case of TSQL, we should think on something like:

```SQL
IF NOT EXISTS (SELECT * FROM [sysobjects] WHERE [name]='MyTable'')
    CREATE TABLE [MyTable](...);
GO
```

Also, we would need a new tool like DbFirst or DbPublish to open the assembly, extract the attributes and structure from the reflection AST and then produce (and even run) the publish script. 
We could even think of a migration tool in the future, but that could take a lot of time, and we are not really using CodeFirst internally. 

I'll give more thought to the idea, maybe there's a good solution that can be added relatively easy. At least for the most common scenarios.

**Comment by turowicz** [comment]
Thanks for rapid answer, I see your point.

DbFirst is useful when migrating between systems, like I currently am switching from MS SQL to Cassandra.

**Comment by pabloordonez** [comment]
I would like to hear how you were thinking this migration. 
Take in mind that if db migration is what you had in mind, is not that simple. You'll need to adapt the Attributes from the MySql database to match cassandra types. Most of them can probably be used as it is.
But, In my experience (and I'm not an expert) is not that simple. Is not only that the paradigms are completely different, the inner works as well. Partition key are not mere primary keys, you need to think about you want to partition your data, how the data will be replicated, obtained or stored. Normally, with cassandra, you want to design your table based on your query, something that would be considered a bad practice in the formal sql world.  Even indices, produce duplicated SSTables or the like to store the same information but indexed by a different key. 
Don't want to sound preachy, it's just friendly advice in case you're new to cassandra/scylla. If you are not, ignore all I said above 😄

**Comment by turowicz** [comment]
I'm not new :) I was originally using Azure Table Storage which is more like Cassandra. Some clients required us to use an on-premise DB so we picked MS SQL. It doesn't make the cut so we are now replacing it with Cassandra.

We don't need any complicated migration, just to generate a database schema creation script.
