### ISSUE TITLE
Is this a correct use of Command and Parameters?

### ISSUE THREAD

**Issue by turowicz** [MiracleDevs/Paradigm.ORM#4]
Is the code below correctly using the parameters?

```c#
using (var context = await _contextFactory())
using (var command = context.CreateCommand())
{
    command.CommandText = $"DELETE FROM some.table WHERE collectionname = @collection AND key = @key";
    command.CommandType = CommandType.Text;

    command.AddParameter("key", typeof(string)).Value = key;
    command.AddParameter("collection", typeof(string)).Value = collectionName;

    await command.ExecuteNonQueryAsync();
}
```

**Comment by turowicz** [comment]
cc @pabloordonez @lbrugnara @bgrainger

**Comment by bgrainger** [comment]
I don't actually know the Paradigm.ORM API very well, but this looks fine to me.

```
command.CommandText = $"
```

This is always a bit of a red flag to me. IMO, interpolated strings should never be used with SQL as it's too easy to cause SQL injection. Always use named parameters instead (which you are doing). Since you're not actually using an interpolated string here, the `$` can be safely removed, avoiding any impression that string interpolation might be getting used.

```
command.CommandType = CommandType.Text;
```

This is usually the default for most ADO.NET providers, so probably can be safely removed.

**Comment by turowicz** [comment]
Thank you @bgrainger! I have used `$` to put in the table with `nameof(MyTable)`. As you can see I've replaced it in the code above with dummy name.
