### ISSUE TITLE
Connection Pooling

### ISSUE THREAD

**Issue by turowicz** [MiracleDevs/Paradigm.ORM#6]
Does the CqlDatabaseConnector support connection pooling and transient recovery or should I create a new connection and open it for each database request?

Currently each of my db calls is wrapped with a new connection being `OpenAsync`-ed.

@pabloordonez @lbrugnara @bgrainger

**Comment by turowicz** [comment]
I've done some testing and it seems like the Cassandra Connector reconnects automatically without having to explicitly call `OpenAsync`

**Comment by pabloordonez** [comment]
@turowicz I made an update a couple of weeks ago, because there was an issue with the ADO.NET implementation of the datastax connector we use internally. Basically, Datastax requries to have one global connection for the same cluster/session pair. You can have multiple connections if you want to connect to a different cluster, but should reuse the same for the same cluster.

Their ADO.NET implementation wraps the cluster session pair with a DbConnection. If you are using the connection for a web scenario, you're probably opening and closing and disposing the connection expecting the inner connector to handle the pool, but that was not what was happening with the driver.

So I took a different approach and added a static cache for cassandra connections. Diposing the connections won't actually dispose the connection. If you want to dispose the connection you'll need to target `CqlConnectionManager.ClearConnections()`.

Disposing connections frequently seemed to also produce a leak inside datastax driver. A lot of pool objects ended up in gen2 and never freed and the application was taking more and more memory.

So far we're seeing much better times and memory management running against a [Scylla](https://www.scylladb.com/) cluster. Sorry for the delay on this.
